# Site settings
title: Adam Baker | Software Developer
email: your-email@domain.com
description: "Adam is a software developer living in Fort Wayne, IN in the US. He is the author of the Google Chrome App 'IT Signature Generator', and when he is not working on code, he is working on classic cars and trucks."
baseurl: "/WebPortfolio"
url: "http://abaker86.github.io"
twitter_username: jekyllrb
github_username:  ABaker86

# Build settings
markdown: kramdown
permalink: pretty
