trigger:
- gh-pages

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '44ddd2e1-c1d5-4817-9d63-fd204e03eaa9'
    pipeline: '3'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'site'
    downloadPath: '$(Build.StagingDirectory)'
    cleanDestinationFolder: true

- script: |
    git config --global user.email "adambaker@live.com"
    git config --global user.name "Adam Baker" 
  displayName: 'set git user info'
  
- script: 'git add .'
  displayName: 'git add all files'

- script : 'git commit -m "azure deploy"'
  displayName: 'git commit with message'

- script: 'git push'
  displayName: 'git push to branch'