trigger:
- gh-pages

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  clean: true
  persistCredentials: true

- script: |
   git config --global user.email "adambaker@live.com"
   git config --global user.name "Adam Baker"
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: 'Set config user name and email'

- script: |
   git fetch --all
   git switch $(basename $(Build.SourceBranch))
  displayName: 'Fetching from "$(basename $(Build.SourceBranch))"'

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '44ddd2e1-c1d5-4817-9d63-fd204e03eaa9'
    pipeline: '3'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'site'
    downloadPath: '$(System.DefaultWorkingDirectory)'
    cleanDestinationFolder: true

- script: |
   git add --all
   git commit -m "deployment $(Build.BuildNumber)"
   git push --set-upstream origin gh-pages 
  displayName: 'commit to branch gh-page at location - "$(System.DefaultWorkingDirectory)"'
  workingDirectory: $(System.DefaultWorkingDirectory)