trigger:
- main

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 3.0'
  
  - script: 'gem install jekyll-paginate'
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'install jekyll-paginate'
  
  - script: 'gem install jekyll bundler'
    workingDirectory: $(Build.SourcesDirectory)
    displayName:  'install bundler'
   
  - script: |
      ls -la;
      bundle install
      jekyll build
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'jekyll build'
  
  - task: CopyFiles@2
    displayName: 'Copy Files from: $(Build.SourcesDirectory)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/DevPortfolio'
      TargetFolder: '$(Build.StagingDirectory)'
  
  
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '*.yml'
      TargetFolder: '$(Build.StagingDirectory)'
    displayName: Copy yml files
  
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.StagingDirectory)'
      artifactName: site