trigger:
- main

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 3.0'
  
  - script: 'gem install jekyll-paginate'
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'install jekyll-paginate'
  
  - script: 'gem install jekyll bundler'
    workingDirectory: $(Build.SourcesDirectory)
    displayName:  'install bundler'
   
  - script: |
      ls -la;
      bundle install
      jekyll build
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'jekyll build'
  
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.SourcesDirectory)'
    inputs:
      TargetFolder: '$(Build.StagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.StagingDirectory)/_site'
      artifactName: site

#build complete
##Push to gh-pages
#
#- job: Deploy
#  pool:
#    vmImage: 'ubuntu-latest'
#  workspace:
#    clean: all
#  steps:
#  - checkout: none #skip checking out the default repository resource
#  #- task: DownloadBuildArtifacts@0
#  #  displayName: 'Download Build Artifacts'
#  #  inputs:
#  #    artifactName: site
#  #    downloadPath: $(Pipeline.Workspace)
#  - script: |
#      git config user.name "ABaker86"
#      git config user.email "adambaker@live.com"
#
#      git clone https://github.com/ABaker86/WebPortfolio.git
#      git checkout gh-pages
#    workingDirectory: $(Build.SourcesDirectory)
#    displayName: 'checkout github branch'
#  - task: DownloadBuildArtifacts@1
#    inputs:
#      buildType: 'specific'
#      project: '44ddd2e1-c1d5-4817-9d63-fd204e03eaa9'
#      pipeline: '3'
#      buildVersionToDownload: 'latest'
#      downloadType: 'specific'
#      downloadPath: '$(Build.StagingDirectory)'
#      cleanDestinationFolder: true
#  - script: |
#      git add .
#      git commit -a m "azure build"
#      git push
#    workingDirectory: $(Build.SourcesDirectory)
#    displayName: 'checkout github branch'
#
#  dependsOn: Build
#  condition: succeeded()